### ISSUE TITLE
How to run DIAYN on softlearning repo ?

### ISSUE THREAD

**Issue by ZhuFengdaaa** [haarnoja/sac#24]
README of this project says that sac is not updated. However, [softlearning](https://github.com/rail-berkeley/softlearning) does not compatible with examples/mujoco_all_diayn.py. Nor does similar DIAYN training code exist in [softlearning](https://github.com/rail-berkeley/softlearning). 

What I can do if I want to run DIAYN on [softlearning](https://github.com/rail-berkeley/softlearning) ?

**Comment by haarnoja** [comment]
Hi, you can still run DIAYN with this code base even though we don't update it anymore. Unfortunately, we are not planning to add DIAYN support to softlearning.

**Comment by hartikainen** [comment]
Also, the official DIAYN repo is found here: https://github.com/ben-eysenbach/sac.
