### ISSUE TITLE
Inquiries about the benchmark results

### ISSUE THREAD

**Issue by anahrendra** [haarnoja/sac#28]
I checked the benchmark results as provided in the github and try to plot the results. However, I noticed that the results are quite different with the results in the paper. Why is that?

For example, the results in the paper for Ant environment shows final performance at almost 6000. However, the raw data given in the benchmark shows only around 4000

Thank you in advance for your time

**Comment by haarnoja** [comment]
Hi,

this repository is not actively maintained anymore, and all of its content has been moved to [https://github.com/rail-berkeley/softlearning](https://github.com/rail-berkeley/softlearning). You should be able to reproduce the results in our paper with the new code base.

Thanks!
